### ISSUE TITLE
API call not working

### ISSUE THREAD

**Issue by unrealkyuan** [ChenYuHo/handwriting.js#1]
https://www.google.com.tw/inputtools/request?ime=handwriting&app=mobilesearch&cs=1&oe=UTF-8 
throws an error, "FAILED_TO_PARSE_REQUEST_BODY"

**Comment by ChenYuHo** [comment]
Hi,
I found it working normally.
What's the request body you sent that throws this error?

**Comment by unrealkyuan** [comment]
@ChenYuHo I simply used the API request that you had already provided in handwriting.canvas.js. Not sure why it's not working for me?

**Comment by ChenYuHo** [comment]
@unrealkyuan 
it should be a POST request with the trace you want to recognize attached in the request body, so I asked what's the request body you sent.

**Comment by unrealkyuan** [comment]
By request body, do you just mean:

 var data = JSON.stringify({
            "options": "enable_pre_space",
            "requests": [{
                "writing_guide": {
                    "writing_area_width": options.width || this.width || undefined,
                    "writing_area_height": options.height || this.width || undefined
                },
                "ink": trace,
                "language": options.language || "zh_TW"
            }]
        });

(sorry, I'm pretty new to using APIs so I apologize if I'm misinterpreting your question. I'm grateful for your patience)

**Comment by ChenYuHo** [comment]
@unrealkyuan 
yes, so what I'm asking is what's inside your "data" variable?
you can print it out.

**Comment by unrealkyuan** [comment]
@ChenYuHo Nevermind, I realized my issue. I forgot to implement a button that would call handwriting.recognize(), so the program was basically just seeing the blank canvas and returning an error. Thanks for the help anyway!
