### ISSUE TITLE
How do you capture a trace

### ISSUE THREAD

**Issue by interstellarcodegit** [ChenYuHo/handwriting.js#3]
I dont  get how we capture a trace

**Comment by ChenYuHo** [comment]
Hi @interstellarcodegit 
Check [here](https://github.com/ChenYuHo/handwriting.js#fully-functional-library) for instructions on a sample implementation that captures a trace through mouse dragging/touchscreen events.
More precisely, the [code](https://github.com/ChenYuHo/handwriting.js/blob/6d41109d3293295a7d7678d0cb97f483d28f47ec/handwriting.canvas.js#L71) here.
You can always implement your own way of capturing user inputs as long as the [format](https://github.com/ChenYuHo/handwriting.js#capture-trace) follows what the library expects.

**Comment by interstellarcodegit** [comment]
Thanks ...solved the issue
